### ISSUE TITLE
cloning repo error

### ISSUE THREAD

**Issue by matebenyovszky** [e2b-dev/ai-developer-with-sandbox#2]
Hi Folks, love the idea, but got this when I tried to start a new project, even after I created an empty repo:

[Sandbox] Cloning repo test-application
[Sandbox] Cloning into 'homeuserrepo'...

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
{
  code: -32000,
  message: "error starting process 'XeuEKXEKsXty': fork/exec /bin/bash: no such file or directory"
}

**Comment by jakubno** [comment]
Hi @matebenyovszky, 

let me understand this better. 
- Do I understand correctly you've just to try run this project on your repo?
- Could you provide the repo on which you tried to run it? 
- Which version of node do you have?

**Comment by matebenyovszky** [comment]
Hi @jakubno , thanks for the quick answer.
1) Yes, I am totally new here 👻
2) To be honest first, I tried to start with a new project - with no repo hoping that it will create that from scratch. That didn't work, so I created an empty project on Github - still not worked. I tried to add some standard files - no success etc.
3) node --version
v20.9.0

**Comment by jakubno** [comment]
Could you share the repo you've tried it on with me?

**Comment by matebenyovszky** [comment]
https://github.com/matebenyovszky/test-algolia-crawler

**Comment by matebenyovszky** [comment]
Do you have any tips what should I do to try your code?

**Comment by jakubno** [comment]
Finally found time to look into this.

The error says you're trying to run process from folder. The actual problem is probably with GitHub login. Are you setting your GITHUB_TOKEN with access to the repo? 

You can read more:
https://docs.github.com/en/enterprise-server@3.6/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

And create the token here:
https://github.com/settings/tokens

I will try to improve the UX, it should raise error, if the login failed. I will also improve the error message in the SDK.

**Comment by jakubno** [comment]
Let me know if it works for you now.

Also you can pull new version, it should help you to navigate to the error

**Comment by matebenyovszky** [comment]
Thank you very much!

Actually I have created the token there. I have updated to the new version, but still no luck.

I got the same error:

```
> ai-developer-with-sandbox@1.0.0 start
> tsx index.ts

√ Enter repo name (eg: username/repo): ... test-algolia-crawler
√ Enter the task you want the AI developer to work on: ... hello world
[Sandbox] Cloning repo test-algolia-crawler
[Sandbox] Cloning into 'homeuserrepo'...

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
{
  code: -32000,
  message: "error starting process 'S36sjDmvX6tJ': fork/exec /bin/bash: no such file or directory"
}

Node.js v20.9.0
``` 

To help to test the issue I intentionally created two another token. One with nearly all permission (resulted with the same error above) and one with intentionally less/bad permissions, but in this case I got a helpful error message:
```

> ai-developer-with-sandbox@1.0.0 start
> tsx index.ts

√ Enter repo name (eg: username/repo): ... test-algolia-crawler
√ Enter the task you want the AI developer to work on: ... hello world
[Sandbox] error validating token: missing required scopes 'repo', 'read:org'      
d:\ClubGPT-ts-e2b\index.ts:49
                throw new Error(`Make sure you've set 'GITHUB_TOKEN' env variable correctly. ${output.stderr}`)
                      ^


Error: Make sure you've set 'GITHUB_TOKEN' env variable correctly. error validating token: missing required scopes 'repo', 'read:org'
    at loginWithGH (d:\ClubGPT-ts-e2b\index.ts:49:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
    at <anonymous> (d:\ClubGPT-ts-e2b\index.ts:225:1)

Node.js v20.9.0
```

Also if the token is totally bad I got a helpful error:
```
> ai-developer-with-sandbox@1.0.0 start
> tsx index.ts

√ Enter repo name (eg: username/repo): ... test-algolia-crawler
√ Enter the task you want the AI developer to work on: ... hello world
[Sandbox] error validating token: HTTP 401: Bad credentials (https://api.github.com/)
[Sandbox] Try authenticating with:  gh auth login
d:\ClubGPT-ts-e2b\index.ts:49
                throw new Error(`Make sure you've set 'GITHUB_TOKEN' env variable correctly. ${output.stderr}`)
                      ^


Error: Make sure you've set 'GITHUB_TOKEN' env variable correctly. error validating token: HTTP 401: Bad credentials (https://api.github.com/)
Try authenticating with:  gh auth login
    at loginWithGH (d:\ClubGPT-ts-e2b\index.ts:49:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
    at <anonymous> (d:\ClubGPT-ts-e2b\index.ts:225:1)

Node.js v20.9.0
```

So I assume the token is right, rather it is some environmental issue. I assume it comes from the sandbox, or it is from my computer? I understand that probably this is some kind of unique thing so I don't want to waste your time, but if I can I am happy to test or share screen etc.

**Comment by jakubno** [comment]
This seems really weird 
<img width="314" alt="image" src="https://github.com/e2b-dev/ai-developer-with-sandbox/assets/50249709/58f0ae65-fcc5-4abf-9201-18b7a5fed88a">
I have 
<img width="360" alt="image" src="https://github.com/e2b-dev/ai-developer-with-sandbox/assets/50249709/d3e69a50-d188-4444-8321-5e17c2b6212d">

Do you see the slashes?  Basically what's happening, the repo is cloned into `homeuserrepo` instead of `home/user/repo`. And then you try to run some process from `home/user/repo => error.

This won't help, but you should also get better output for your error, if you run `npm install`, I released new version of SDK, which should better explain, what's going on.

Now let's find out, why is this happening... On what system are you running? Mac, Linux, Windows?

**Comment by matebenyovszky** [comment]
Windows 11
Got same errors on powershell and git bash terminal.

```
PS D:\ClubGPT-ts-e2b> npm install

removed 1 package, changed 1 package, and audited 80 packages in 1s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\ClubGPT-ts-e2b> npm run start

> ai-developer-with-sandbox@1.0.0 start
> tsx index.ts

√ Enter repo name (eg: username/repo): ... test-algolia-crawler
√ Enter the task you want the AI developer to work on: ... hello world
[Sandbox] Cloning repo test-algolia-crawler
[Sandbox] Cloning into 'homeuserrepo'...
D:\ClubGPT-ts-e2b\node_modules\@e2b\sdk\dist\index.js:1274
              throw new CurrentWorkingDirectoryDoesntExistError(
                    ^

CurrentWorkingDirectoryDoesntExistError: Failed to start the process. You are trying set 'cwd' to a directory that does not exist.
error starting process 'ekhIC7exGlHm': fork/exec /bin/bash: no such file or directory       
    at Sandbox.<anonymous> (D:\ClubGPT-ts-e2b\node_modules\@e2b\sdk\dist\index.js:1274:21)  
    at Generator.next (<anonymous>)
    at fulfilled (D:\ClubGPT-ts-e2b\node_modules\@e2b\sdk\dist\index.js:52:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0
```

**Comment by jakubno** [comment]
Can you try something for me, change line 32 from `const repoDirPath = path.join(...)` to
```js
const repoDirPath = /home/user/repo
```

I suspect the path is resolved differently on Windows, causing this issue

**Comment by matebenyovszky** [comment]
Yep, will try in a minute, my pair programmer friend GPT4 told me sg similar:
![image](https://github.com/e2b-dev/ai-developer-with-sandbox/assets/57362482/0cbf7cd6-935f-4d1d-aa7e-7f11ef4ab0d3)

**Comment by matebenyovszky** [comment]
This works!!!

```typescript
const repoDirPath = '/home/user/repo'
```

**Comment by matebenyovszky** [comment]
Some extra info:
const repoDirPath = path.join('home', 'user', 'repo');    --> [Sandbox] Cloning into 'homeuserrepo'... (slashes missing, error)
const repoDirPath = path.posix.join('home', 'user', 'repo');  --> [Sandbox] Cloning into 'home/user/repo'... (starting / missing, error)
const repoDirPath = path.posix.join(rootdir, repoDir); --> [Sandbox] Cloning into '/home/user/repo'... (Works!!)

Thanks you for working this out!
